
services:
  
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "4317:4317"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
      

  service_a:
    container_name: service_a
    build:
      context: .
      dockerfile: service_a/Dockerfile
    depends_on:
      - zipkin
      - otel-collector
      - service_b
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - WEATHER_SERVICE=http://service_b:8080
    ports:
      - 8000:8000

  service_b:
    container_name: service_b
    build:
      context: .
      dockerfile: service_b/Dockerfile
    depends_on:
      - zipkin
      - otel-collector
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - WEATHERAPI_KEY
    ports:
      - 8080:8080



