### Resultado OK
POST http://localhost:8000/
Content-Type: application/json

{
    "cep": "01001000"
}

### Resultado 422 invalid zipcode
POST http://localhost:8000/
Content-Type: application/json

{
    "cep": "0100100"
}

### Resultado Cep Inexistente
POST http://localhost:8000/
Content-Type: application/json

{
    "cep": "12345678"
}


### Resultado Teste do cep do desafio
POST http://localhost:8000/
Content-Type: application/json

{
    "cep": "29902555"
}

